version: '3.1'
services: 

  mongo_db:
    image: mongo
    ports: 
    - 27017:27017     # position of the port number has a new line and a minus why? Convention? Why this port number?
    restart: always

  postgres_sql:
    image: postgres
    ports:
    - 5555:5432
    restart: always   
    environment:
      POSTGRES_USER: marco   # default is postgres, so in this case not necessary
      POSTGRES_DB: analysis_results_d
      POSTGRES_PASSWORD: affffen10

  tweet_collector:
    build: tweet_collector/
    volumes: 
    - ./tweet_collector/src_tweet_collector:/app
    depends_on:
    - mongo_db

  sentiment_analysis:
    build: sentiment_analysis/
    volumes: 
    - ./sentiment_analysis/src_analysis:/app
    depends_on:
    - mongo_db
    - postgres_sql

  slack_bot:
    build: slack_bot/
    volumes: 
    - ./slack_bot/src_slack_bot:/app
    depends_on:
    - postgres_sql